name: Test

on:
  workflow_dispatch:
    
jobs:
  UpdateChangeDetails:
    runs-on: ubuntu-latest
    name: Servicenow Update Change Details

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Servicenow Update Change Details
        uses: ServiceNow/servicenow-devops-update-change@v3.1.0
        id: update
        with:
          change-request-number: 'CHG1167786'
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}

         # devops-integration-user-name: 'devops.integration.user'
         # devops-integration-user-password: '3o7xwdM2GN1K2iQp'
          instance-url: 'https://usps13.servicenowservices.com'
          context-github: ${{ toJSON(github) }}
          change-request-details: '{"short_description": "MKMK Test description in Updated by Github custom Action"}'
      - name: Output of UpdateChangeDetails
        run: echo "The Status of Update Change Request Details => ${{ steps.update.outputs.status }}"
