name: Test

on:
  workflow_dispatch:
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm ci

    - name: Compile
      run: npm run build
  UpdateChangeDetails:
    needs: build
    runs-on: ubuntu-latest
    name: Servicenow Update Change Details

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Servicenow Update Change Details
        uses: ServiceNow/servicenow-devops-update-change@v3.1.0
        id: update
        with:
          change-request-number: 'CHG0030004'
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          context-github: ${{ toJSON(github) }}
          change-request-details: '{"short_description": "Test description in Updated by Github custom Action","description":"Automated Software Deployment.","close_code":"successful", "close_notes":"Closing during Github Actions CustomActionUpdate","state":"3"}'
      - name: Output of UpdateChangeDetails
        run: echo "The Status of Update Change Request Details => ${{ steps.update.outputs.status }}"
